### ISSUE TITLE
Invalid link in the Authentication Template and Wallet Template

### ISSUE THREAD

**Issue by kiok46** [bitauth/bitauth-ide#104]
The [authentication-template-v0.schema.json](https://github.com/bitauth/bitauth-ide/blob/master/public/authentication-template-v0.schema.json#L27)  and [libauth wallet template](https://libauth.org/types/WalletTemplate.html#__type._schema) have an invalid link resulting in 404.

Invalid link: (https://libauth.org/schemas/wallet-template-v0.schema.json)

**Comment by bitjson** [comment]
Fixed, thanks @kiok46!
