### ISSUE TITLE
OP_TOALTSTACK is an unknown opcode

### ISSUE THREAD

**Issue by jcramer** [bitauth/bitauth-ide#16]
The first opcode in one of my script is OP_TOALTSTACK and I got a message: `Called an unknown opcode.`

**Comment by bitjson** [comment]
Hey @jcramer, thanks for opening an issue! And sorry to take so long to get back to you. I've been working on finishing the [VM implementation](https://github.com/bitauth/bitcoin-ts/tree/41097c440a0ac0c21184e76383f866b2015768e9/src/lib/auth/instruction-sets/bch), I'm hoping to have it released this week. I'll let you know here are soon as it's up.

**Comment by bitjson** [comment]
@jcramer thanks for opening an issue, and sorry for the delay! 

I just released an [update to bitcoin-ts](https://medium.com/@bitjson/evaluate-and-debug-bitcoin-cash-scripts-in-javascript-3e182136000d) which includes the rest of the BCH virtual machine. You should now be able to debug any valid BCH program properly. 

Please let me know if you find any other unexpected behavior.
