### ISSUE TITLE
Flickering

### ISSUE THREAD

**Issue by readcash** [bitauth/bitauth-ide#37]
A small bug: 

1) import CashChannels https://ide.bitauth.com/import-gist/ca13abf369b5ecace6437cb86afa331f 
2) enable reverse order 
3) open Execute Authorization (Oracle)  
4) try to scroll the script - the stack constantly switches from "normal" to "reverse" ordering on each scroll event

**Comment by bitjson** [comment]
@readcash thanks for the report! 

I'm having trouble reproducing this now – I'm not sure if it was a bug earlier which I fixed (as part of a larger refactor) or if it's still an issue. Are you still able to reproduce?

(If so, any chance you could provide a little more detail on how to reproduce it? Are stack items actually switching places? Or is it a problem with the UI lagging?)

**Comment by slava-vishnyakov** [comment]
Yes, the flickering is gone! Thanks!

**Comment by readcash** [comment]
It works, thanks!
