### ISSUE TITLE
When switching between entities, the name and entity_id does not change. 

### ISSUE THREAD

**Issue by lilayoung** [bitauth/bitauth-ide#68]
Using Chrome Version 97.0.4692.71 (Official Build) (x86_64) on Mac: 

Notice keys on the right are showing we are at signer1, signer2, signer3 respectively, but name and entity ID fields stay the same as those belonging to signer2. 
 
![Screen Shot 2022-01-25 at 2 46 15 PM](https://user-images.githubusercontent.com/52258235/151073345-fb191a1a-7c6e-4ca4-9aba-7ee18f29123d.png)
![Screen Shot 2022-01-25 at 2 46 20 PM](https://user-images.githubusercontent.com/52258235/151073352-5f7eb44a-319d-486f-b8e6-9b0d4dede41c.png)
![Screen Shot 2022-01-25 at 2 46 26 PM](https://user-images.githubusercontent.com/52258235/151073357-2de32c2c-cd6e-4b4e-a293-2cb7a7720fcb.png)

The same behavior is observed when creating a new script from scratch and adding multiple entities.

**Comment by bitjson** [comment]
Thank you very much for opening this issue @lilayoung! Sorry for the delay, this is resolved as of `v1.0.0`, and the `can switch between entities`[screenshot](https://github.com/bitauth/bitauth-ide/blob/9047128c197d7f283cf53a9551b5fd49bdb976ca/tests/entity-settings.spec.ts-snapshots/can-switch-between-entities-1-chromium-linux.png)-based [test](https://github.com/bitauth/bitauth-ide/blob/9047128c197d7f283cf53a9551b5fd49bdb976ca/tests/entity-settings.spec.ts#L98-L131) even covers this exact case. 🚀
